FROM ubuntu:22.04
ARG CPUNUM=12
ARG TAG=llvmorg-16.0.6
ARG GCC_TAG=2023.06.09

ENV DEBIAN_FRONTEND=noninteractive
RUN apt update && apt install -y \
    cmake \
    ccache \
    ninja-build \
    git \
    g++ \
    python3

# 📄 Clone repository
RUN git clone \
        -b ${TAG} \
        --depth=1 \
        --recurse-submodules \
        --shallow-submodules \
        https://github.com/llvm/llvm-project
WORKDIR llvm-project

# 🛠 Build toolchain
RUN cmake \
    -S llvm \
    -B build \
    -G Ninja \
    -DLLVM_ENABLE_PROJECTS='clang;clang-tools-extra;lldb;lld;compiler-rt' \
    -DLLVM_ENABLE_RUNTIMES="libcxx;libcxxabi;libunwind" \
    -DCMAKE_BUILD_TYPE=Release
RUN cmake --build build --target install

# Add GCC-collab toolchain for libstdc++
ADD https://github.com/riscv-collab/riscv-gnu-toolchain/releases/download/${GCC_TAG}/riscv64-glibc-ubuntu-22.04-nightly-${GCC_TAG}-nightly.tar.gz /opt
RUN cd /opt && tar -xf *.tar.gz