FROM ubuntu:22.04
ARG CPUNUM=12

ENV DEBIAN_FRONTEND=noninteractive
RUN apt update && apt install -y \
    cmake \
    ccache \
    ninja-build \
    git \
    curl \
    python3 \
    python3-pip \
    unzip

ADD http://localhost:8000/riscv64-linux-x86_64-20210618.zip /riscv-toolchain/

RUN cd /riscv-toolchain  \
    && unzip riscv64-linux-x86_64-20210618.zip \
    && cd riscv64-linux-x86_64-20210618 \
    && cp -rvf * /usr/local